### ISSUE TITLE
First time leave event was not triggered on flex items

### ISSUE THREAD

**Issue by fede91it** [silvestreh/onScreen#47]
Hello,

I have this script to monitor when a element will enter or leave the viewpoint.

```js
$(function() {
    var os = new OnScreen();
    var header = $('.top-bar');

    os.on('enter', '#header', function() {
        console.log('enter');
    });

    os.on('leave', '#header', function() {
        console.log('leave');
    });
});
```

The markup is this:

```html
<header id="header">
    <div class="row align-right top-bar animated">
        <div class="column">
            <div class="sub-column">
                ...
            </div>
            <div class="sub-column">
                ...
            </div>
        </div>
    </div>
</header>
```

**Case 1 (issued)**

```css
.sub-column {
    display: flex;
    align-items: center;
}
```

On page loading `enter` event was triggered. I scroll the page and the `leave` event do not triggers. I return to top of the page and `enter` triggers, so I scoll down for the second time and only not the `leave` event triggers. After this point all entering and leaving triggers.

I register the same behavior when I try to use a table-like layout:

```css
.sub-column {
    display: table-cell;
}
```

**Case 2**

```css
.sub-column {
    display: block;
}
```

On page loading `enter` event was triggered. I scroll the page and the `leave` event was triggered. The behaviour repeats as expected, so it's working fine.
